# The items in this configuration file correspond to the steps in the overall recipe.
# The values refer to configuration files of the individual steps.

defaults:
  - .@paths: ../paths
  - .@shared: ../shared
  - .@setup: setup
  - .@validate: validate
  - .@prepare: prepare
  - .@evaluate: evaluate
  - .@report: report
  - _self_

# Info for which signals to evaluate
segment_types: [individual, summed] # Types of reference segments to process
devices: [aria, ha] # Devices to process
dataset: dev # Dataset to use for processing
sample_rate: ${shared.ref_sample_rate}

# Setting up paths for outputs of the experiments
evaluation_dir: ${paths.evaluation_dir}

# Directories and paths where outputs are produced
segment_dir: ${evaluation_dir}/segments/{device}/{segment_type}
results_file: ${evaluation_dir}/results/results.{dataset}.{device}.{segment_type}.json
report_file: ${evaluation_dir}/reports/report.{dataset}.{device}.{segment_type}.{session}.{pid}.json

hydra:
  run:
    dir: ${evaluation_dir}/hydra
  job_logging:
    root:
      level: INFO

# If you wish to skip a step, set its value to null or true as below.
# This can be also done from command-line when running the script, e.g.
# python run.py setup.run=false
setup:
  run: true
validate:
  run: true
prepare:
  run: true
evaluate:
  run: true
report:
  run: true
