# GPU-free configuration for testing purposes

# signal related metrics
# -- sir: signal to interference ratio
# -- sar: signal to artifact ratio
# -- sdr: signal to distortion ratio
# -- ci-sdr: scale-invariant signal to distortion ratio
# -- si-snri: scale-invariant signal to noise ratio improvement
- name: pysepm
- name: signal_metric

# pesq related metrics
- name: pesq

# stoi related metrics
# -- stoi: short-time objective intelligibility
- name: stoi

