input_signal_file: ${..paths.ref_signal_file}
segment_info_file: ${..paths.segment_info_file}
segment_sample_rate: ${..sample_rate}

output_segment_dir: ${..paths.ref_segment_dir}

dataset: ${dataset}
devices: ${devices}
sessions_file: ${..paths.sessions_file}
