dataset: ${dataset}
devices: ${devices}

noisy_signal: ${..paths.echi_signal}
enhanced_signal: ${..paths.enhancement_output_file}
sessions_file: ${..paths.sessions_file}

expected_sample_rate: ${..shared.ref_sample_rate}
expected_bitdepth: ${..shared.signal_bitdepth}
expected_nchannels: ${..shared.nchannels}