# The items in this configuration file correspond to the steps in the overall recipe.
# The values refer to configuration files of the individual steps.

defaults:
  - .@paths: ../paths
  - .@shared: ../shared
  - .@unpack: unpack
  - .@dataloading: dataloading
  - .@train: train
  - .@model: model
  - .@wandb: wandb
  - _self_

# Signal info
device: aria
audio_channels: 7
model_sample_rate: ${shared.model_sample_rate}
ref_sample_rate: ${shared.ref_sample_rate}

# Debug run
debug: false

# Setting up paths for outputs of the experiments
train_dir: ${paths.train_aria_dir}
hydra:
  run:
    dir: ${train_dir}/hydra
  job_logging:
    root:
      level: INFO

# If you wish to skip a step, set its value to null or true as below.
# This can be also done from command-line when running the script, e.g.
# python run.py prepare_data.run=false
unpack:
  run: true
train:
  run: true
