input_signal_file: ${..paths.ref_signal_file}
segment_info_file: ${..paths.segment_info_file}
segment_sample_rate: ${..shared.sample_rate}

output_segment_dir: ${..paths.train_target_dir}

dataset: [train, dev]
devices: [ha, aria]
sessions_file: ${..paths.sessions_file}
