# Path to where the submitted data is stored
enhanced_dir: ${..paths.enhanced_dir}

results_file: ${..paths.results_file}

segment_dir: ${..paths.segment_dir}

csv_dir: ${..paths.echi}/metadata/ref/dev # Path to the CSV files for evaluation
ref_segment_dir: ${..paths.ref_segment_dir} # Path to the reference segment directory

signal_id: ${..paths.signal_id} # naming convention for signals e.g. session.device.pid

score_config: config/metrics.yaml
#score_config: config/metrics_test.yaml

use_gpu: false

# For parallel evaluation
batch: 1
n_batches: 1

dataset: ${..shared.dataset}
devices: ${..shared.devices}

sessions_file: ${..paths.sessions_file}
