input_signal_dir: ${..paths.signal_dir}
segment_info_dir: ${..paths.segment_info_dir}
segment_sample_rate: ${..shared.sample_rate}

output_segment_dir: ${..paths.device_segment_dir}

dataset: [train, dev]
devices: [ha, aria]
sessions_file: ${..paths.sessions_file}

translate_id: device_wav