input_signal_dir: ${..paths.ref_signal_dir}
segment_info_dir: ${..paths.segment_info_dir}
segment_sample_rate: ${..shared.sample_rate}

output_segment_dir: ${..paths.ref_segment_dir}

dataset: ${..shared.dataset}
devices: [ha, aria]
sessions_file: ${..paths.sessions_file}

translate_id: pid_wav