ref_signal_file: ${..paths.ref_signal_file}
segment_info_file: ${..paths.segment_info_file}

ref_segment_dir: ${..paths.ref_segment_dir}

dataset: ${..shared.dataset}
devices: [ha, aria]
sessions_file: ${..paths.sessions_file}
