# Configuration parameters shared across modules

devices: [ha, aria] # Devices to process
dataset: dev # Dataset to use for processing
sample_rate: 16000 # Reference sample rate.

exp: exp # Experiment name - change this to create a new experiment
