experiment_name: testing
datastore: data
debug: true
run_tracker: ${datastore}/HydraLogs/test_tracker.json
dataset:
  name: chime9_echi
  metadata: ${datastore}/${dataset.name}/{subset}_sessions.csv
  audio_dir: ${datastore}/chime9_echi
  device: aria
  onesession: false
  signal:
    noisy_sr: 16000
    ref_sr: 16000
    spk_sr: 16000
    n_channels: 7
  train:
    order: random
    loader:
      batch_size: 1
      shuffle: true
      num_workers: 4
      drop_last: true
      pin_memory: true
  dev:
    order: random
    loader:
      batch_size: 1
      shuffle: false
      num_workers: 4
      drop_last: true
      pin_memory: true
  eval:
    order: random
    loader:
      batch_size: 1
      shuffle: false
      num_workers: 4
      drop_last: true
      pin_memory: true
model:
  name: causalmcxtfgridnet
  input:
    sample_rate: 16000
    channels: ${dataset.signal.n_channels}
    rms: 0.05
    use_spkid: true
    type: stft
    stft:
      n_fft: 128
      win_length: 128
      hop_length: 64
      window: hann
  params:
    n_srcs: 1
    n_imics: ${model.input.channels}
    n_layers: 3
    lstm_hidden_units: 128
    attn_n_head: 4
    attn_qk_output_channel: 128
    emb_dim: 48
    emb_ks: 4
    emb_hs: 1
    activation: prelu
    eps: 1.0e-05
trainer:
  name: default
  epochs: 5
  checkpoint_interval: 2
  schedule_lr: false
  lr: 0.001
  loss:
    name: spec
    kwargs:
      fft_size: 1024
      hop_size: 256
      win_length: 1024
      window: hann_window
      w_sc: 1.0
      w_log_mag: 1.0
      w_lin_mag: 0.0
      w_phs: 0.0
      sample_rate: null
      scale: null
      n_bins: null
      perceptual_weighting: false
      scale_invariance: false
      eps: 1.0e-08
      output: loss
      reduction: mean
      mag_distance: L1
wandb:
  entity: robbiesuth97-university-of-sheffield
  project: echi-baseline-dev
hydra:
  run:
    dir: ${datastore}/hydra/train/testing