# The items in this configuration file correspond to the steps in the overall recipe.
# The values refer to configuration files of the individual steps.

defaults:
  - .@paths: ../paths
  - .@shared: ../shared
  - enhance_args: ../baseline
  - _self_

# Experiment name
exp_name: ${shared.exp_name}
enhancement_name: ${exp_name}

# Info for which signals to evaluate
device: aria # Devices to process
dataset: dev # Dataset to use for processing

model_sample_rate: ${shared.model_sample_rate}
ref_sample_rate: ${shared.ref_sample_rate}
bitdepth: ${shared.signal_bitdepth}

# Input filepaths
noisy_signal: ${paths.echi_signal}
rainbow_signal: ${paths.rainbow_signal_file}

enhanced_signal: ${paths.enhanced_signal}
sessions_file: ${paths.sessions_file}

# Setting up paths for outputs of the experiments
base_dir: ${paths.scratch}/experiments/${shared.exp_name}/inference
hydra:
  run:
    dir: ${base_dir}/hydra
  job_logging:
    root:
      level: INFO

# If you wish to skip a step, set its value to null or true as below.
# This can be also done from command-line when running the script, e.g.
# python run.py setup.run=false